---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
reclaimPolicy: Delete
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
  fsType: xfs
  shared: "yes"