---
# Source: nginx-ingress-controller/templates/controller-metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nginx-ingress-controller-metrics
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-9.7.7
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/port: '9913'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9913
      targetPort: metrics
  selector:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: controller
