---
# Source: lvm-localpv/templates/lvm-node-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-lvm-localpv-node-service
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    name: "openebs-lvm-node"
    release: release-name
    openebs.io/component-name: "openebs-lvm-node"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9500
      targetPort: 9500
  selector:
    app: openebs-lvm-node
