---
# Source: lvm-localpv/templates/lvm-controller.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-lvm-localpv-controller
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    app: "openebs-lvm-controller"
    release: release-name
    component: "openebs-lvm-controller"
    openebs.io/component-name: "openebs-lvm-controller"
spec:
  selector:
    matchLabels:
      app: "openebs-lvm-controller"
      release: release-name
      component: "openebs-lvm-controller"
  serviceName: "openebs-lvm"
  replicas: 1
  template:
    metadata:
      labels:
        chart: lvm-localpv-1.2.0
        heritage: Helm
        openebs.io/version: "1.2.0"
        role: "openebs-lvm"
        app: "openebs-lvm-controller"
        release: release-name
        component: "openebs-lvm-controller"
        openebs.io/component-name: "openebs-lvm-controller"
        
        name: openebs-lvm-controller
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - openebs-lvm-controller
            topologyKey: "kubernetes.io/hostname"
      priorityClassName: release-name-lvm-localpv-csi-controller-critical
      serviceAccountName: openebs-lvm-controller-sa
      containers:
        - name: csi-resizer
          image: "registry.cn-hangzhou.aliyuncs.com/google_containers/csi-resizer:v1.8.0"
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              cpu: 100m
              memory: 320Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: csi-snapshotter
          image: "registry.cn-hangzhou.aliyuncs.com/google_containers/csi-snapshotter:v6.2.2"
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              cpu: 100m
              memory: 320Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: snapshot-controller
          image: "registry.cn-hangzhou.aliyuncs.com/google_containers/snapshot-controller:v6.2.2"
          args:
            - "--v=5"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 320Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: csi-provisioner
          image: "registry.cn-hangzhou.aliyuncs.com/google_containers/csi-provisioner:v3.5.0"
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
            - "--enable-capacity=true"
            - "--extra-create-metadata=true"
            - "--default-fstype=ext4"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              cpu: 100m
              memory: 320Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: openebs-lvm-plugin
          image: "openebs/lvm-driver:1.2.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENEBS_CONTROLLER_DRIVER
              value: controller
            - name: OPENEBS_CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: LVM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPENEBS_IO_INSTALLER_TYPE
              value: "lvm-localpv-helm"
            - name: OPENEBS_IO_ENABLE_ANALYTICS
              value: "true"
          args :
            - "--endpoint=$(OPENEBS_CSI_ENDPOINT)"
            - "--plugin=$(OPENEBS_CONTROLLER_DRIVER)"
            - "--kube-api-qps=0"
            - "--kube-api-burst=0"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              cpu: 100m
              memory: 320Mi
            requests:
              cpu: 10m
              memory: 32Mi
      volumes:
        - name: socket-dir
          emptyDir: {}
