---
# Source: lvm-localpv/templates/rbac.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: openebs-lvm-controller-sa
  namespace: default
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    app: "openebs-lvm-controller"
    release: release-name
    component: "openebs-lvm-controller"
    openebs.io/component-name: "openebs-lvm-controller"
---
# Source: lvm-localpv/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-lvm-node-sa
  namespace: default
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    name: "openebs-lvm-node"
    release: release-name
    openebs.io/component-name: "openebs-lvm-node"
---
# Source: lvm-localpv/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openebs-lvm-provisioner-role
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    app: "openebs-lvm-controller"
    release: release-name
    component: "openebs-lvm-controller"
    openebs.io/component-name: "openebs-lvm-controller"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "services"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csistoragecapacities"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["local.openebs.io"]
    resources: ["lvmvolumes", "lvmsnapshots", "lvmnodes"]
    verbs: ["*"]
---
# Source: lvm-localpv/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openebs-lvm-snapshotter-role
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    app: "openebs-lvm-controller"
    release: release-name
    component: "openebs-lvm-controller"
    openebs.io/component-name: "openebs-lvm-controller"
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]
---
# Source: lvm-localpv/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openebs-lvm-driver-registrar-role
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    name: "openebs-lvm-node"
    release: release-name
    openebs.io/component-name: "openebs-lvm-node"
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["local.openebs.io"]
    resources: ["lvmvolumes", "lvmsnapshots", "lvmnodes"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# Source: lvm-localpv/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openebs-lvm-provisioner-binding
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    app: "openebs-lvm-controller"
    release: release-name
    component: "openebs-lvm-controller"
    openebs.io/component-name: "openebs-lvm-controller"
subjects:
  - kind: ServiceAccount
    name: openebs-lvm-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: openebs-lvm-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: lvm-localpv/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openebs-lvm-snapshotter-binding
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    app: "openebs-lvm-controller"
    release: release-name
    component: "openebs-lvm-controller"
    openebs.io/component-name: "openebs-lvm-controller"
subjects:
  - kind: ServiceAccount
    name: openebs-lvm-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: openebs-lvm-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: lvm-localpv/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openebs-lvm-driver-registrar-binding
  labels:
    chart: lvm-localpv-1.2.0
    heritage: Helm
    openebs.io/version: "1.2.0"
    role: "openebs-lvm"
    name: "openebs-lvm-node"
    release: release-name
    openebs.io/component-name: "openebs-lvm-node"
subjects:
  - kind: ServiceAccount
    name: openebs-lvm-node-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: openebs-lvm-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
