apiVersion: node.k8s.io/v1
handler: kata-clh
kind: RuntimeClass
metadata:
  name: kata-clh
overhead:
  podFixed:
    cpu: 250m
    memory: 130Mi
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"