apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-clh
  labels:
    name: nginx-deployment-clh
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      runtimeClassName: kata
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
