# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  generateName: rook-ceph-mon-a-56db4b4444-
  labels:
    app: rook-ceph-mon
    app.kubernetes.io/component: cephclusters.ceph.rook.io
    app.kubernetes.io/created-by: rook-ceph-operator
    app.kubernetes.io/instance: a
    app.kubernetes.io/managed-by: rook-ceph-operator
    app.kubernetes.io/name: ceph-mon
    app.kubernetes.io/part-of: rook-ceph
    ceph_daemon_id: a
    ceph_daemon_type: mon
    mon: a
    mon_cluster: rook-ceph
    pod-template-hash: 56db4b4444
    rook.io/operator-namespace: rook-ceph
    rook_cluster: rook-ceph
  name: rook-ceph-mon-a-56db4b4444-b7zw4
  namespace: rook-ceph
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: rook-ceph-mon-a-56db4b4444
      uid: 41167b65-f56f-476a-a3fa-0e4afc76dbf4
spec:
  affinity: {}
  containers:
    - name: mon
      args:
        - --fsid=b46dad43-1e60-4480-9435-914637eb6d74
        - --keyring=/etc/ceph/keyring-store/keyring
        - --default-log-to-stderr=true
        - --default-err-to-stderr=true
        - --default-mon-cluster-log-to-stderr=true
        - '--default-log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=a
        - --setuser=ceph
        - --setgroup=ceph
        - --foreground
        - --public-addr=172.30.0.98
        - --setuser-match-path=/var/lib/ceph/mon/ceph-a/store.db
      command:
        - ceph-mon
      env:
        - name: CONTAINER_IMAGE
          value: registry.cn-shanghai.aliyuncs.com/shilintan-public/quay.io_ceph_ceph:v17.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: CEPH_USE_RANDOM_NONCE
          value: "true"
        - name: ROOK_MSGR2
          value: msgr2_true_encryption_false_compression_false
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: ROOK_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      image: registry.cn-shanghai.aliyuncs.com/shilintan-public/quay.io_ceph_ceph:v17.2.6
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - env
            - -i
            - sh
            - -c
            - "\noutp=\"$(ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status 2>&1)\"\nrc=$?\nif
          [ $rc -ne 0 ]; then\n\techo \"ceph daemon health check failed with the following
          output:\"\n\techo \"$outp\" | sed -e 's/^/> /g'\n\texit $rc\nfi\n"
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      ports:
        - containerPort: 3300
          hostPort: 3300
          name: tcp-msgr2
          protocol: TCP
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        privileged: false
      startupProbe:
        exec:
          command:
            - env
            - -i
            - sh
            - -c
            - "\noutp=\"$(ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status 2>&1)\"\nrc=$?\nif
          [ $rc -ne 0 ]; then\n\techo \"ceph daemon health check failed with the following
          output:\"\n\techo \"$outp\" | sed -e 's/^/> /g'\n\texit $rc\nfi\n"
        failureThreshold: 6
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /run/ceph
          name: ceph-daemons-sock-dir
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-4nqbc
          readOnly: true
      workingDir: /var/log/ceph
    - name: log-collector
      command:
        - /bin/bash
        - -x
        - -e
        - -m
        - -c
        - "\nCEPH_CLIENT_ID=ceph-mon.a\nPERIODICITY=daily\nLOG_ROTATE_CEPH_FILE=/etc/logrotate.d/ceph\nLOG_MAX_SIZE=500M\nROTATE=7\n\n#
      edit the logrotate file to only rotate a specific daemon log\n# otherwise we
      will logrotate log files without reloading certain daemons\n# this might happen
      when multiple daemons run on the same machine\nsed -i \"s|*.log|$CEPH_CLIENT_ID.log|\"
      \"$LOG_ROTATE_CEPH_FILE\"\n\n# replace default daily with given user input\nsed
      --in-place \"s/daily/$PERIODICITY/g\" \"$LOG_ROTATE_CEPH_FILE\"\n\n# replace
      rotate count, default 7 for all ceph daemons other than rbd-mirror\nsed --in-place
      \"s/rotate 7/rotate $ROTATE/g\" \"$LOG_ROTATE_CEPH_FILE\"\n\nif [ \"$LOG_MAX_SIZE\"
      != \"0\" ]; then\n\t# adding maxsize $LOG_MAX_SIZE at the 4th line of the logrotate
      config file with 4 spaces to maintain indentation\n\tsed --in-place \"4i \\
      \\ \\ \\ maxsize $LOG_MAX_SIZE\" \"$LOG_ROTATE_CEPH_FILE\"\nfi\n\nwhile true;
      do\n\t# we don't force the logrorate but we let the logrotate binary handle
      the rotation based on user's input for periodicity and size\n\tlogrotate --verbose
      \"$LOG_ROTATE_CEPH_FILE\"\n\tsleep 15m\ndone\n"
      image: registry.cn-shanghai.aliyuncs.com/shilintan-public/quay.io_ceph_ceph:v17.2.6
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        privileged: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /run/ceph
          name: ceph-daemons-sock-dir
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-4nqbc
          readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
    - args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /run/ceph
        - /var/lib/ceph/mon/ceph-a
      command:
        - chown
      image: registry.cn-shanghai.aliyuncs.com/shilintan-public/quay.io_ceph_ceph:v17.2.6
      imagePullPolicy: IfNotPresent
      name: chown-container-data-dir
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        privileged: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /run/ceph
          name: ceph-daemons-sock-dir
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-4nqbc
          readOnly: true
    - name: init-mon-fs
      args:
        - --fsid=b46dad43-1e60-4480-9435-914637eb6d74
        - --keyring=/etc/ceph/keyring-store/keyring
        - --default-log-to-stderr=true
        - --default-err-to-stderr=true
        - --default-mon-cluster-log-to-stderr=true
        - '--default-log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=a
        - --setuser=ceph
        - --setgroup=ceph
        - --public-addr=172.30.0.98
        - --mkfs
      command:
        - ceph-mon
      env:
        - name: CONTAINER_IMAGE
          value: registry.cn-shanghai.aliyuncs.com/shilintan-public/quay.io_ceph_ceph:v17.2.6
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: CEPH_USE_RANDOM_NONCE
          value: "true"
        - name: ROOK_MSGR2
          value: msgr2_true_encryption_false_compression_false
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
      image: registry.cn-shanghai.aliyuncs.com/shilintan-public/quay.io_ceph_ceph:v17.2.6
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        privileged: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /run/ceph
          name: ceph-daemons-sock-dir
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-4nqbc
          readOnly: true
  nodeName: k8s-1
  nodeSelector:
    kubernetes.io/hostname: k8s-1
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: rook-config-override
      projected:
        defaultMode: 420
        sources:
          - configMap:
              items:
                - key: config
                  mode: 292
                  path: ceph.conf
              name: rook-config-override
    - name: rook-ceph-mons-keyring
      secret:
        defaultMode: 420
        secretName: rook-ceph-mons-keyring
    - hostPath:
        path: /var/lib/rook/exporter
        type: DirectoryOrCreate
      name: ceph-daemons-sock-dir
    - hostPath:
        path: /var/lib/rook/rook-ceph/log
        type: ""
      name: rook-ceph-log
    - hostPath:
        path: /var/lib/rook/rook-ceph/crash
        type: ""
      name: rook-ceph-crash
    - hostPath:
        path: /var/lib/rook/mon-a/data
        type: ""
      name: ceph-daemon-data
    - name: kube-api-access-4nqbc
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace